# Generated by Django 5.2 on 2025-06-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0006_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
