# Generated by Django 5.1.7 on 2025-06-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0007_delete_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
