# Generated by Django 5.1.7 on 2025-06-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0008_booking_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='amount',
        ),
    ]
