# Generated by Django 5.2 on 2025-06-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle_number',
            new_name='vehicle',
        ),
    ]
