# Generated by Django 5.2 on 2025-06-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0002_rename_vehicle_number_booking_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='vehicle',
            new_name='vehicle_number',
        ),
    ]
