# Generated by Django 5.2 on 2025-06-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0003_rename_vehicle_booking_vehicle_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='user',
            new_name='user_id',
        ),
    ]
