# Generated by Django 5.2 on 2025-06-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Autocareapp', '0004_rename_user_booking_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Autocareapp.userprofile'),
        ),
    ]
